---

- name: Build docker image
  gather_facts: false
  hosts: all
  tasks:
    - name: Copy Dockerfile file to all hostmachines
      copy: src=./Dockerfile
            dest=./
    - name: Remove image
      community.docker.docker_image:
       state: absent
       name: abc-technology
       tag: v1
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
       build:
        path: ~/
       name: abc-technology
       tag: v1
       source: build
    - name: Stop a container, if running
      docker_container:
       name: ABCtechnology
       state: stopped
    - name: remove container
      docker_container:
       name: ABCtechnology
       state: absent
    - name: Create a container
      docker_container:
       name: ABCtechnology
       image: abc-technology:v1
       ports:
        - "8080:80"  
...
