---

- name: Build docker image & deploy on docker container
  gather_facts: false
  hosts: all
  tasks:
    - name: Build the image
      hosts: 127.0.0.1
      connection: local
      community.docker.docker_image:
       build:
        path: ~/
       name: abc-technology
       tag: v1
       source: build
    - name: Stop the container, if running
      docker_container:
       name: ABCtechnology
       image: abc-technology:v1
       state: stopped
    - name: Remove container
      docker_container:
       name: ABCtechnology
       image: abc-technology:v1
       state: absent
    - name: Remove image
      community.docker.docker_image:
       state: absent
       name: abc-technology
       tag: v1
    - name: Tag and push to docker hub
      docker_image:
       name: abc-technology
       repository: arunbuee/abc-technology
       tag: v1
       push: yes
    - name: Pull image from dockerhub repo
      docker_image:
       name: arunbuee/abc-technology:v1
    - name: Create the container
      docker_container:
       name: ABCtechnology
       image: abc-technology:v1
       ports:
        - "80:8080"  
...
